services:
  web:
    build: ./fe
    depends_on:
      - backend-service
    ports:
      - "5002:5002"
    networks:
      - mynet
    environment:
      BACKEND_API_URL: http://backend-service:5001/fetch_price

  backend-service:
    build: ./be
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "5003:5001"
    networks:
      - mynet
    environment:
      MYSQL_HOST: mysqldb  
      MYSQL_USER: root
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: crypto_db

  mysqldb:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: "123456"
        # create database name crypto_db
        MYSQL_DATABASE: crypto_db
    ports:
      - "3306:3306"
    networks:
      - mynet
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  db_data:

networks:
  mynet:
    driver: bridge





      