apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  selector:
    matchLabels:
      app: mysqldb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - image: mysql:5.7
        name: mysqldb
        env:
        - name: MYSQL_ROOT_PASSWORD   
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password   #123456
        - name: MYSQL_DATABASE
          value: "crypto_db"  
        ports:
        - containerPort: 3306
          name: mysqldb
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service #Clusterip
spec:
  selector:
    app: mysqldb
  ports:
  - port: 3306