apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
      - name: backend
        image: morandan7/myimages:mybackend
        ports:
        - containerPort: 5001
        env: 
        - name: MYSQL_HOST
          value: "mysqldb"  
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password   #"123456"
        - name: MYSQL_DATABASE
          value: "crypto_db"
---
apiVersion: v1
kind: Service
metadata:
  name: myclusterip   #by default
  labels:
    app: backend-service
spec:
  selector:
      app: backend-service
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  

