apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
spec:
  selector:
    matchLabels:
      app: redis-cluster
  serviceName: "redis" 
  replicas: 3
  template:
    metadata:
      labels:
        app: redis-cluster
    spec:
      containers:
      - name: redis-con
        image: redis:6.2.5
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: myvolume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: myvolume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
