apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: http-con
        image: hashicorp/http-echo
        args:
        - "-text=Hello, World!"
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: myclusterip
  labels:
    app: my-app0
spec:
  selector:
      app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678
  
