services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    container_name: flask
    depends_on:
      - postgres
    build: .
    ports:
      - "5005:5000"  
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydatabase

volumes:
  postgres_data:
