apiVersion: v1
kind: Pod
metadata:
  name: volume-app
  labels:
    name: volume-app
spec:
  containers:
    - name: nginx-main
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-storage
          mountPath: /app/shared-data  # Shared directory for logs and files

    - name: springapp
      image: yanivomc/spring-music:latest
      ports: 
        - containerPort: 8080
      volumeMounts:
        - name: shared-storage
          mountPath: /app/shared-data  # Shared with Nginx
      command: ["sh", "-c"]
      args:
        - java -jar /app/spring-music.jar --logging.file=/app/shared-data

  volumes:
    - name: shared-storage
      hostPath:
        path: /tmp/shared-volume  # Shared host directory
        type: DirectoryOrCreate
