apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: reviews
spec:
  parentRefs:
  - name: bookinfo-gateway
  # The following will override our reviews service endpoint controller and 
  # will pass the traffic only to reviews-v1
  - group: ""            #API group
    kind: Service
    name: reviews
    port: 9080
  rules:
  - backendRefs:
    - name: reviews-v1
      port: 9080